// Data export utilities for CSV and ESG reports
import type { BrandData } from "./auth"

export interface ESGMetrics {
  recyclablePercentage: number
  carbonFootprint: number
  sustainabilityScore: number
  materialEfficiency: number
  wasteReduction: number
}

export function generateCSV(data: BrandData[], filename: string): void {
  const headers = ["ID", "Brand", "Material", "Confidence Score", "Material Detection", "Timestamp"]
  const csvContent = [
    headers.join(","),
    ...data.map((item) =>
      [
        item.id,
        item.name,
        item.material,
        (item.confidence.brand_recognition * 100).toFixed(2) + "%",
        (item.confidence.material_detection * 100).toFixed(2) + "%",
        new Date(item.timestamp).toLocaleString(),
      ].join(","),
    ),
  ].join("\n")

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" })
  const link = document.createElement("a")
  const url = URL.createObjectURL(blob)
  link.setAttribute("href", url)
  link.setAttribute("download", `${filename}.csv`)
  link.style.visibility = "hidden"
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export function calculateESGMetrics(data: BrandData[]): ESGMetrics {
  if (!data || data.length === 0) {
    return {
      recyclablePercentage: 0,
      carbonFootprint: 100,       // assume max footprint if no data
      sustainabilityScore: 0,
      materialEfficiency: 0,
      wasteReduction: 0,
    }
  }
const recyclableMaterials = ["Aluminum Can", "Glass Bottle", "Cardboard"]
  const recyclableCount = data.filter((item) =>
    recyclableMaterials.includes(item.material),
  ).length

  const recyclablePercentage = (recyclableCount / data.length) * 100

  // Mock calculations for other metrics
  const carbonFootprint = Math.max(0, 100 - recyclablePercentage * 0.8)
  const sustainabilityScore = Math.min(100, recyclablePercentage * 1.2)
  const materialEfficiency = Math.random() * 20 + 75 // 75–95%
  const wasteReduction = Math.random() * 15 + 10    // 10–25%

  return {
    recyclablePercentage,
    carbonFootprint,
    sustainabilityScore,
    materialEfficiency,
    wasteReduction,
  }
}

export function generateESGReport(brand: string, data: BrandData[], metrics: ESGMetrics): string {
  const reportDate = new Date().toLocaleDateString()

  return `
# ESG Sustainability Report - ${brand}
Generated on: ${reportDate}

## Executive Summary
This report provides an analysis of ${brand}'s environmental, social, and governance (ESG) performance based on packaging material analysis and brand detection data.

## Key Metrics

### Environmental Impact
- **Recyclable Materials**: ${metrics.recyclablePercentage.toFixed(1)}%
- **Carbon Footprint Score**: ${metrics.carbonFootprint.toFixed(1)}/100
- **Sustainability Score**: ${metrics.sustainabilityScore.toFixed(1)}/100
- **Material Efficiency**: ${metrics.materialEfficiency.toFixed(1)}%
- **Waste Reduction**: ${metrics.wasteReduction.toFixed(1)}%

### Material Breakdown
${data.reduce(
  (acc, item) => {
    acc[item.material] = (acc[item.material] || 0) + 1
    return acc
  },
  {} as Record<string, number>,
)}

### Data Quality
- **Total Items Analyzed**: ${data.length}
- **Average Brand Recognition Confidence**: ${((data.reduce((sum, item) => sum + item.confidence.brand_recognition, 0) / data.length) * 100).toFixed(1)}%
- **Average Material Detection Confidence**: ${((data.reduce((sum, item) => sum + item.confidence.material_detection, 0) / data.length) * 100).toFixed(1)}%

## Recommendations
1. **Increase Recyclable Packaging**: Current recyclable percentage is ${metrics.recyclablePercentage.toFixed(1)}%. Target: 80%+
2. **Material Optimization**: Focus on aluminum and glass alternatives where feasible
3. **Supply Chain Transparency**: Improve tracking of packaging materials throughout the supply chain
4. **Consumer Education**: Develop programs to educate consumers about proper recycling practices

## Compliance Status
- ✅ EU Packaging Directive compliance
- ✅ Circular Economy Action Plan alignment
- ⚠️  Carbon neutrality targets (in progress)
- ✅ Material disclosure requirements

---
Report generated by FMCG Analytics Platform
`
}
